# Generated by Django 4.2.7 on 2025-08-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('hours', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=255)),
                ('original_source', models.CharField(max_length=255)),
                ('original_link', models.TextField()),
                ('owner', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='KPIStatus',
        ),
    ]
